name: LWJGL Build

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  mac:
    name: Build mac natives
    runs-on: macos-latest
    env:
      ANT_OPTS: -Xmx8G
      LWJGL_BUILD_TYPE: stable
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 3
    
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'
    
      - run: |
          mkdir jdk8
          curl -L https://cdn.azul.com/zulu/bin/zulu8.70.0.23-ca-fx-jdk8.0.372-macosx_x64.tar.gz | tar xz -C jdk8 --strip-components 1     
        name: Install dependencies
     
      - name: Compile templates
        run: ant compile-templates
        
      - name: Compile natives for x64
        env:
          LWJGL_BUILD_ARCH: x64
        run: ant compile-native
      - name: Compile natives for arm64
        env:
          LWJGL_BUILD_ARCH: arm64
        run: ant compile-native
        
      - name: Compress artifacts
        run: zip -r macos-libs-all.zip macos
        working-directory: bin/libs/native
        
      - name: Upload artifacts (GCS)
        uses: google-github-actions/upload-cloud-storage@v1.0.3
        with:
          destination: lwjgl-bucket-stock
          path: bin/libs/native/macos-libs-all.zip
      
  release:
    name: Build linux natives
    runs-on: ubuntu-22.04
    env:
      ANT_OPTS: -Xmx6G
      LWJGL_BUILD_TYPE: stable
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.3
    
      - name: Set up gcloud Cloud SDK environment
        uses: google-github-actions/setup-gcloud@v1.1.1
    
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'
    
      - name: Install packages
        run: | 
          sudo apt update -y
          sudo apt install ant build-essential zip git make gcc-arm-linux-gnueabihf g++-arm-linux-gnueabihf gcc-aarch64-linux-gnu g++-aarch64-linux-gnu -y
        
      - name: Compile templates
        run: ant compile-templates
        
      - name: Compile natives for x64
        env:
          LWJGL_BUILD_ARCH: x64
        run: ant compile-native
      - name: Compile natives for arm32
        env:
          LWJGL_BUILD_ARCH: arm32
        run: ant compile-native
      - name: Compile natives for arm64
        env:
          LWJGL_BUILD_ARCH: arm64
        run: ant compile-native
        
      - name: Compress artifacts
        run: zip -r linux-libs-all.zip linux
        working-directory: bin/libs/native
          
      - name: Upload artifacts (GCS)
        uses: google-github-actions/upload-cloud-storage@v1.0.3
        with:
          destination: lwjgl-bucket-stock
          path: bin/libs/native/linux-libs-all.zip

  windows:
    name: Windows
    runs-on: windows-latest
    env:
      ANT_OPTS: -Xmx4G
      JAVA_HOME: zulu8.70.0.23-ca-fx-jdk8.0.372-win_x64
      LWJGL_BUILD_ARCH: x64
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 3
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'  
        
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: amd64
      - run: git clone https://github.com/LWJGL-CI/OculusSDK.git ../OculusSDK
        name: Clone Oculus SDK
        
      - run: |
          Invoke-WebRequest https://cdn.azul.com/zulu/bin/zulu8.70.0.23-ca-fx-jdk8.0.372-win_x64.zip -OutFile jdk.zip
          Expand-Archive -Path jdk.zip -DestinationPath .\
        name: Install dependencies
     
      - name: Compile templates
        run: ant compile-templates
        
      - name: Compile natives for x64
        run: ant compile-native
        
      - name: Compress artifacts
        run: Compress-Archive -Path windows -DestinationPath windows-libs-amd64.zip
        working-directory: bin/libs/native
        
      - name: Upload artifacts (GCS)
        uses: google-github-actions/upload-cloud-storage@v1.0.3
        with:
          destination: lwjgl-bucket-stock
          path: bin/libs/native/windows-libs-amd64.zip
